### PR TITLE
TPTP4X testing

### LINKED ISSUE #197: TPTP4X Testing Fails on Mac
The TPTP4X binary must have been compiled on a different OS. For instance, the command

./tests/examples/tptp4X <problem.p>

produces error

zsh: exec format error: ./tests/examples/tptp4X

### PR DESCRIPTION
**Pull request by janheuer**
Fixes #197 by adding a Mac binary and then determining which binary to use by checking the OS. For a OS different from Mac or linux the tptp test is ignored.

### CODE REVIEW

File: tests/examples/main.rs [hunk 1]
```diff
@@ -39,7 +40,7 @@ impl Test {
             })
     }
 
-    fn execute(&self) {
+    fn execute(&self, tptp4x_name: &str) {
```
Comment (teiesti) [inline tests/examples/main.rs]: Please don't have an additional argument here. Pick the proper binary within this function.

**Review by teiesti — CHANGES_REQUESTED** [review]

**Review by teiesti — APPROVED** [review]
