### PR TITLE
Fix issue #234

### LINKED ISSUE #234: Substitute is bugged for Formulas (quantified subformula case)
substitute(var: Variable, term: GeneralTerm) within F:

GeneralTerm encompasses variables, so we need to check that 
(1) the quantification variables do not contain the var (which we are doing) but also that 
(2) the term we are replacing var with does not contain variables occurring in the quantification (needs to be done)

### PR DESCRIPTION
**Pull request by teiesti**
Closes #234

### CODE REVIEW

File: src/syntax_tree/fol.rs [hunk 1]
```diff
@@ -647,6 +657,15 @@ pub struct Variable {
 
 impl_node!(Variable, Format, VariableParser);
 
+impl Variable {
+    fn sequence(prefix: &Variable) -> impl Iterator<Item = Self> {
+        (1..).map(|i| Variable {
+            name: format!("{}_{}", prefix.name, i),
```
Comment (ZachJHansen) [inline src/syntax_tree/fol.rs]: Let's use "{}{}" instead of "{}_{}" for consistency with how tau-star creates fresh variable names for now. At some point we can revisit how fresh variable naming is handled

Comment (teiesti) [reply src/syntax_tree/fol.rs]: Okay, let's do this. At some point we should consolidate generating new variables as a public function in the syntax tree.

Comment (teiesti) [reply src/syntax_tree/fol.rs]: I've created issue #238 for that.

**Review by ZachJHansen — APPROVED** [review]
